# Based on "raild" by dkeg
# https://github.com/dkeg/crayolo

# Default colors
[colors.primary]
background = '#1d1b19'
foreground = '#dbdace'

dim_foreground    = '#1d1b19'
bright_foreground = '#dbdace'

# Cursor colors
[colors.cursor]
text   = '#dbdace'
cursor = '#d9d9d9'

# Normal colors
[colors.normal]
black   = '#282623'
red     = '#935334'
green   = '#66604d'
yellow  = '#ad8b67'
blue    = '#9c7d36'
magenta = '#634737'
cyan    = '#5a6648'
white   = '#bcbba4'

# Bright colors
[colors.bright]
black   = '#43403b'
red     = '#c76e42'
green   = '#998e60'
yellow  = '#e0ae70'
blue    = '#d2a949'
magenta = '#965a42'
cyan    = '#6c804e'
white   = '#ad8b67'

# Dim colors
[colors.dim]
black   = '#282623'
red     = '#935334'
green   = '#66604d'
yellow  = '#ad8b67'
blue    = '#9c7d36'
magenta = '#634737'
cyan    = '#5a6648'
white   = '#bcbba4'
