shell = "/usr/bin/fish"

[window]
padding = { x = 10, y = 10}

[font]
normal = { family = "BigBlueTermPlus Nerd Font Mono", style = "Regular" }
bold = { family = "BigBlueTermPlus Nerd Font Mono", style = "Bold" }
italic = { family = "BigBlueTermPlus Nerd Font Mono", style = "Italic" }
bold_italic = { family = "BigBlueTermPlus Nerd Font Mono", style = "Bold Italic" }
size = 10
