shell = "/usr/bin/fish"

import = ["~/.cache/wal/colors-alacritty.toml"]

[window]
padding = { x = 10, y = 10}
opacity = 0.9
blur = true

[font]
normal = { family = "BigBlueTermPlus Nerd Font Mono", style = "Regular" }
bold = { family = "BigBlueTermPlus Nerd Font Mono", style = "Bold" }
italic = { family = "BigBlueTermPlus Nerd Font Mono", style = "Italic" }
bold_italic = { family = "BigBlueTermPlus Nerd Font Mono", style = "Bold Italic" }
size = 11

[cursor]
style = {shape = "Block",blinking = "On"}
blink_interval = 1000
blink_timeout = 0

[mouse]
hide_when_typing = true

