# key template for convenience
# key = { fg = "#ffffff", bg = "#000000", underline = { color = "#ff0000", style = "curl"}, modifiers = ["bold", "italic"] }

inherits = "base16_transparent"

# "ui.selection" = { bg = "background", underline = { color = "slate"}}

"ui.linenr" = { fg = "light-drab" }
"ui.linenr.selected" = { fg = "light-copper", bg = "light-slate" }

# "ui.selection" = {fg = "black", bg = "gray"} #fg is text, bg is selection

[palette]
background = "#1d1b19"
foreground = "#dbdace"
slate = "#282623"
copper = "#935334"
drab = "#66604d"
tan = "#ad8b67"
gold = "#9c7d36"
clay = "#634737"
sage = "#5a6648"
marble = "#bcbba4"

light-slate = "#43403b"
light-copper = "#c76e42"
light-drab = "#998e60"
light-tan = "#e0ae70"
light-gold = "#d2a949"
light-clay = "#965a42"
light-sage = "#6c804e"

medium-tan = "#ad8b67"

debug-pink = "#ff00ff"
debug-green = "#00ff00"
