#! /bin/sh

# # Set up monitor orientation and refresh rate (3 monitors)

# # Remember that you can use ArandR to set up positioning graphically, then put its outputs here

# #xrandr --output DVI-D-0 --mode 1600x900 --pos 2560x414 --rotate normal --output HDMI-0 --mode 2560x1440 --pos 0x0 --rotate normal --output DP-0 --primary --mode 2560x1440 --pos 1600x0 --rotate normal --rate 144 --output DP-1 --off --output DVI-D-1 --off

# # Set up monitor orientation and refresh rate (2 monitors)

xrandr --output DVI-D-0 --mode 1600x900 --pos 2560x400 --rotate normal --output HDMI-0 --primary --mode 2560x1440 --pos 0x0 --rotate normal --output DP-0 --off --output DP-1 --off --output DVI-D-1 --off

# # Start important programs/change important settings

setxkbmap -option ctrl:swapcaps
pgrep -x sxhkd > /dev/null || sxhkd &
picom  &
wal -R 

# # set colors automatically using wal's current theme
# source the colors
. "${HOME}/.cache/wal/colors.sh"
# Set the border colors.
bspc config focused_border_color "$color6" #focused window on the current desktop
bspc config active_border_color "$color5" #focused window on any other desktop
bspc config normal_border_color "$color1" #all other windows
bspc config presel_feedback_color "$color5" #preselection color

# playerctld daemon & (memory issues)
/home/lea/.config/polybar/colorblocks/launch.sh &
dropbox start &
xinput set-prop 'COOLERMASTER CM310' 'Coordinate Transformation Matrix' 1 0 0 0 1 0 0 0 1.5 &
mullvad connect & 

# # Set desktops to monitors

# # 3 monitor setup
# bspc monitor DP-0 -d 4 5 6 7
# bspc monitor HDMI-0 -d 1 2 3
# bspc monitor DVI-D-0 -d 8 9 10

# # 2 monitor setup
bspc monitor HDMI-0 -d 1 2 3 4 5
bspc monitor DVI-D-0 -d 6 7 8 9 10

# # 1 monitor setup
# bspc monitor HDMI-0 -d 1 2 3 4 5 6 7 8 9 10

# # Make steam games go to a fullscreen window in desktop 6

# steamlib=/media/gamedisk/SteamLibrary # path to your steamlibrary
# mygames=$(ls $steamlib/steamapps/common/appmanifest_*.acf | sed 's/[0^9]*//g') # this sed command removes everything but the digits



bspc config border_width		3
bspc config window_gap			12
bspc config focus_follows_pointer	true

bspc config split_ratio			0.55
bspc config borderless_monocle		false
bspc config gapless_monocle		false

bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a Chromium desktop='^2'
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off
bspc rule -a RuneLite state=floating
bspc rule -a Discord desktop='^6'
bspc rule -a discord desktop='^6'
bspc rule -a steam desktop='^4'
bspc rule -a Steam desktop='^4'
# bspc rule -a Steam state=floating
bspc rule -a Zathura state=tiled
