theme = "base16_transparent_modified"

[editor]

shell = ["fish", "-c"]
line-number = "relative"
bufferline = "multiple"
color-modes = true

[editor.cursor-shape]
normal = "block"
insert = "block"
select = "underline"

[editor.soft-wrap]
enable = true

[editor.statusline]
right = ["diagnostics", "selections", "register", "position", "primary-selection-length", "file-encoding"]

[keys.normal]
d = "move_char_left"
D = "swap_view_left"
h = "move_visual_line_down"
H = "join_selections"
t = "move_visual_line_up"
T = "keep_selections"
n = "move_char_right"
N = "swap_view_right"
j = "delete_selection"
J = "workspace_diagnostics_picker"
k = "find_till_char"
K = "till_prev_char"
l = "search_next"
L = "search_prev"

[keys.normal.z]
d = "move_char_left"
D = "swap_view_left"
h = "move_visual_line_down"
H = "join_selections"
n = "move_char_right"
N = "swap_view_right"
j = "delete_selection"
J = "workspace_diagnostics_picker"
k = "find_till_char"
K = "till_prev_char"
l = "search_next"
L = "search_prev"

[keys.normal.g]
u = "goto_line_start"

[keys.select]
d = "move_char_left"
D = "swap_view_left"
h = "move_visual_line_down"
H = "join_selections"
t = "move_visual_line_up"
T = "keep_selections"
n = "move_char_right"
N = "swap_view_right"
j = "delete_selection"
J = "workspace_diagnostics_picker"
k = "find_till_char"
K = "till_prev_char"
"C-c" = "normal_mode"
l = "search_next"
L = "search_prev"

[keys.select.g]
u = "goto_line_start"

[keys.insert]
"C-c" = "normal_mode"
# "C-Backspace" = "delete_word_backward"
