theme = "base16_transparent_modified"

[editor]

shell = ["fish", "-c"]
line-number = "relative"
bufferline = "multiple"
color-modes = true

[editor.cursor-shape]
normal = "block"
insert = "block"
select = "underline"

[editor.soft-wrap]
enable = true

[editor.statusline]
right = ["diagnostics", "selections", "register", "position", "primary-selection-length", "file-encoding"]

[editor.smart-tab]
enable = false

[keys.normal]
m = "move_char_left"
M = "swap_view_left"
n = "move_visual_line_down"
N = "join_selections"
e = "move_visual_line_up"
E = "keep_selections"
i = "move_char_right"
I = "swap_view_right"
l = "search_next"
L = "search_prev"
k = "move_next_word_end"
K = "move_next_long_word_end"
j = "yank"
J = "yank_main_selection_to_clipboard"
y = "insert_mode"
Y = "insert_at_line_start"

[keys.normal.z]
n = "scroll_down"
e = "scroll_up"
l = "search_next"
L = "search_prev"
o = "align_view_top"

[keys.normal.Z]
n = "scroll_down"
e = "scroll_up"
l = "search_next"
L = "search_prev"
o = "align_view_top"

[keys.normal.h]
h = "match_brackets"
s = "surround_add"
r = "surround_replace"
d = "surround_delete"
a = "select_textobject_around"
i = "select_textobject_inner"

[keys.normal.g]
m = "goto_line_start"
n = "move_line_down"
e = "move_line_up"
i = "goto_line_end"
k = "goto_last_line"

[keys.normal.C-w]
m = "jump_view_left"
C-m = "jump_view_left"
n = "jump_view_down"
C-n = "jump_view_down"
e = "jump_view_up"
C-e = "jump_view_up"
i = "jump_view_right"
C-i = "jump_view_right"
M = "swap_view_left"
N = "swap_view_down"
E = "swap_view_up"
I = "swap_view_right"

[keys.normal.space]
j = "yank_to_clipboard"
J = "yank_main_selection_to_clipboard"
y = "jumplist_picker"

[keys.select]
m = "move_char_left"
M = "swap_view_left"
n = "move_visual_line_down"
N = "join_selections"
e = "move_visual_line_up"
E = "keep_selections"
i = "move_char_right"
I = "swap_view_right"
l = "search_next"
L = "search_prev"
k = "move_next_word_end"
K = "move_next_long_word_end"
j = "yank"
J = "yank_main_selection_to_clipboard"
y = "insert_mode"
Y = "insert_at_line_start"

[keys.select.z]
n = "scroll_down"
e = "scroll_up"
l = "search_next"
L = "search_prev"
o = "align_view_top"

[keys.select.Z]
n = "scroll_down"
e = "scroll_up"
l = "search_next"
L = "search_prev"
o = "align_view_top"

[keys.select.h]
h = "match_brackets"
s = "surround_add"
r = "surround_replace"
d = "surround_delete"
a = "select_textobject_around"
i = "select_textobject_inner"

[keys.select.g]
m = "goto_line_start"
n = "move_line_down"
e = "move_line_up"
i = "goto_line_end"
k = "goto_last_line"

[keys.select.C-w]
m = "jump_view_left"
C-m = "jump_view_left"
n = "jump_view_down"
C-n = "jump_view_down"
e = "jump_view_up"
C-e = "jump_view_up"
i = "jump_view_right"
C-i = "jump_view_right"
M = "swap_view_left"
N = "swap_view_down"
E = "swap_view_up"
I = "swap_view_right"

[keys.select.space]
j = "yank_to_clipboard"
J = "yank_main_selection_to_clipboard"
y = "jumplist_picker"

[keys.insert]
"C-space" = "normal_mode"
C-v = "record_macro"
C-q = "replay_macro"
# "C-Backspace" = "delete_word_backward"
