[[language]]
name = "arst"
scope = "source.txt"
file-types = ["txt", "", "kbd"]
comment-tokens = "#"
indent = { tab-width = 4, unit = "\t"}

[[language]]
name = "javascript"
indent = { tab-width = 4, unit = "\t"}

[[language]]
name = "css"
indent = { tab-width = 4, unit = "\t"}

[[language]]
name = "c"
indent = { tab-width = 4, unit = "\t"}

[[language]]
name = "fish"
indent = { tab-width = 4, unit = "\t"}

[[language]]
name = "bash"
indent = { tab-width = 4, unit = "\t"}

[[language]]
name = "markdown"
indent = { tab-width = 4, unit = "\t"}

[[language]]
name = "common-lisp"
indent = { tab-width = 4, unit = "\t"}

[[language]]
name = "lua"
indent = { tab-width = 4, unit = "\t"}

[[language]]
name = "hocon"
indent = { tab-width = 4, unit = "\t"}
