#!/usr/bin/env sh

#
# wm independent hotkeys
#

# terminal emulator
super + Return
	alacritty

# program launcher
super + @space
	rofi -show combi -modes combi -combi-modes "drun,run"

# make sxhkd reload its configuration files:
super + Escape
	pkill -USR1 -x sxhkd

# launch lf
super + r
	alacritty -e lf

# launch browser
super + alt + b
	firefox

# take a screenshot using maim, either of the current desktop, the active window, or a region;
# copies the image to the clipboard and saves it to the screenshots directory using a filename with the date
super + shift + o; {k,o,p}
	maim {-w root -g 2560x1440+0+0,-i $(xdotool getactivewindow),-s} | xclip -selection clipboard -t image/png && xclip -selection clipboard -t image/png -o > ~/pictures/screenshots/$(date +%Y-%m-%d_%H:%M.png)

# copy primary selection to a helix window for editing, then put it on the clipboard
super + e
	scratchpad

# take a screenshot of a screen region using maim, perform OCR on it with tesseract, and pass the resulting text to the clipboard (currently in portuguese for Carmine reasons)
super + shift + o; r
	maim -s | tesseract - - -l por | xclip -selection clipboard

# speak the clipboard with espeak using bookreport
super + shift + s;{s,k}
	{bookreport --clipboard,killall -q espeak}

# toggle the keymap between dvorak and colemak
super + alt + @space
	setxkbmap -query | grep -q 'dvorak' && setxkbmap -variant colemak || setxkbmap -variant dvorak

#
# bspwm hotkeys
#

# quit/restart bspwm
super + alt + {q,r}
	bspc {quit,wm -r}

# close and kill
super + {_,shift + }w
	bspc node -{c,k}

# alternate between the tiled and monocle layout
super + m
	bspc desktop -l next

# send the newest marked node to the newest preselected node
super + y
	bspc node newest.marked.local -n newest.!automatic.local

# swap the current node and the biggest window
super + g
	bspc node -s biggest.window

#
# state/flags
#

# set the window state
super + {i,shift + i,s,f}
	bspc node -t {tiled,pseudo_tiled,floating,fullscreen}

# set the node flags
super + ctrl + {m,v,x,y,z}
	bspc node -g {marked,hidden,locked,sticky,private}

# unhide all hidden windows
super + u 
	bspc node any.hidden.local -g hidden

# hide the focused node, and swap it with the most recently hidden node on the same desktop
super + l
	bspc node any.hidden.local -g hidden=off && bspc node -g hidden
	

#
# focus/swap
#

# focus the node in the given direction
super + {d,h,t,n}
	bspc node -f {west,south,north,east}

# focus the node for the given path jump
super + {p,b,comma,period}
	bspc node -f @{parent,brother,first,second}

# focus the next/previous window in the current desktop
super + {_,shift + }c
	bspc node -f {next,prev}.local.!hidden.window

# focus the next/previous desktop in the current monitor
super + bracket{left,right}
	bspc desktop -f {prev,next}.local

# focus the last node/desktop
super + {grave,Tab}
	bspc {node,desktop} -f last

# focus the older or newer node in the focus history
super + {o,i}
	bspc wm -h off; \
	bspc node {older,newer} -f; \
	bspc wm -h on

# focus or send to the given desktop
super + {_,shift + }{1-9,0}
	bspc {desktop -f,node -d} {1-9,10}
#super + alt + {6,7,8,9,0}
#	bspc {desktop -f,node -d} {11,12,13,14,15}
super + alt + {_,shift + }{6,7,8,9,0}
	bspc {desktop -f,node -d} {11,12,13,14,15}

# swap the selected node with the node in the given direction
super + alt + {d,h,t,n}
	bspc node -s {west,south,north,east}

#
# preselect
#

# preselect the direction
super + ctrl + shift + {d,h,t,n}
	bspc node -p {west,south,north,east}

# preselect the ratio
super + ctrl + {1-9}
	bspc node -o 0.{1-9}

# cancel the preselection for the focused node
super + ctrl + space
	bspc node -p cancel

# cancel the preselection for the focused desktop
super + ctrl + shift + space
	bspc query -N -d | xargs -I id -n 1 bspc node id -p cancel

#
# move/resize
#

# expand a window by moving one of its side outward
super + ctrl + {d,h,t,n}
	bspc node -z {left -20 0,bottom 0 20,top 0 -20,right 20 0}

# contract a window by moving one of its side inward
super +  shift + {d,h,t,n}
	bspc node -z {right -20 0,top 0 20,bottom 0 -20,left 20 0}

# move a floating window
super + {Left,Down,Up,Right}
	bspc node -v {-20 0,0 20,0 -20,20 0}

# rotate currently selected node
super + ctrl + {r,shift+r}
	bspc node -R {90,-90}
