#!/usr/bin/env sh

#
# wm independent hotkeys
#

# terminal emulator
super {_,shift + }+ Return
	alacritty {_,--class float }-e tmux new

# program launcher
super + @space
	rofi -show combi -modes combi -combi-modes "drun,run"

# make sxhkd reload its configuration files:
super + Escape
	pkill -USR1 -x sxhkd

# launch ranger
super {_,shift + } + q
	alacritty {_,--class float }-e tmux new -- ranger

# launch browser
super + alt + b
	zen-browser

# take a screenshot using flameshot
super + shift + s
	flameshot gui

# copy clipboard to a helix window for editing, then put it back on the clipboard
super + d
	scratchpad

# take a screenshot of a screen region using maim, perform OCR on it with tesseract, and pass the resulting text to the clipboard (currently in portuguese for Carmine reasons)
super + shift + o; r
	maim -s | tesseract - - -l por | xclip -selection clipboard

# speak the clipboard with espeak using bookreport
super + alt + k
	pgrep espeak || bookreport --clipboard

# make espeak be quiet
super + Tab
	killall -q espeak
# hide and unhide discord
super + {}

#
# bspwm hotkeys
#

# quit/restart bspwm
super + alt + {q,r}
	bspc {quit,wm -r}

# close and kill
super + {_,shift + }w
	bspc node -{c,k}

# alternate between the tiled and monocle layout
super + j
	bspc desktop -l next
super + h
	bspc desktop -l next

# send the newest marked node to the newest preselected node
super + y
	bspc node newest.marked.local -n newest.!automatic.local

# swap the current node and the biggest window
super + g
	bspc node -s biggest.window

# send the focused node to the "above" layer
super + ctrl + alt + l
	bspc node -l above

#
# state/flags
#

# set the window state
super + {t,shift + t,s,f}
	bspc node -t {tiled,pseudo_tiled,floating,fullscreen}

# set the node flags
super + ctrl + {h,v,x,y,z}
	bspc node -g {marked,hidden,locked,sticky,private}

# special hidden flag hotkey because she's useful
super + v
	bspc node -g hidden

# unhide all hidden windows
super + l 
	bspc node any.hidden.local -g hidden

# hide the focused node, and swap it with the most recently hidden node on the same desktop
super + u
	bspc node any.hidden.local -g hidden=off && bspc node -g hidden
	

#
# focus/swap
#

# focus the node in the given direction
super + {p,n,e,a}
	bspc node -f {west,south,north,east}

# focus the node for the given path jump
super + {m,b,comma,period}
	bspc node -f @{parent,brother,first,second}

# focus the next/previous window in the current desktop
super + {_,shift + }c
	bspc node -f {next,prev}.local.!hidden.window

# focus the next/previous desktop in the current monitor
super + bracket{left,right}
	bspc desktop -f {prev,next}.local

# focus the last node/desktop
alt + Tab
	bspc node -f last.local

# focus the older or newer node in the focus history
# super + {o,i}
	# bspc wm -h off; \
	# bspc node {older,newer} -f; \
	# bspc wm -h on

# focus or send to the given desktop
super + {_,shift + }{1,2,3,4,5,7,8,9,0,minus}
	bspc {desktop -f,node -d} {1,2,3,4,5,6,7,8,9,10}
#super + alt + {6,7,8,9,0}
#	bspc {desktop -f,node -d} {11,12,13,14,15}
super + alt + {_,shift + }{7,8,9,0,minus}
	bspc {desktop -f,node -d} {11,12,13,14,15}
super + alt + -
	bspc desktop -f 15

# swap the selected node with the node in the given direction
super + alt + {p,n,e,a}
	bspc node -s {west,south,north,east}

#
# preselect
#

# preselect the direction
super + ctrl + shift + {p,n,e,a}
	bspc node -p {west,south,north,east}

# preselect the ratio
super + ctrl + {1-9}
	bspc node -o 0.{1-9}

# cancel the preselection for the focused node
super + ctrl + space
	bspc node -p cancel

# cancel the preselection for the focused desktop
super + ctrl + shift + space
	bspc query -N -d | xargs -I id -n 1 bspc node id -p cancel

#
# move/resize
#

# expand a window by moving one of its side outward
super + ctrl + {p,n,e,a}
	bspc node -z {left -20 0,bottom 0 20,top 0 -20,right 20 0}

# contract a window by moving one of its side inward
super +  shift + {p,n,e,a}
	bspc node -z {right -20 0,top 0 20,bottom 0 -20,left 20 0}

# move a floating window
super + {p,n,e,a}
	bspc node -v {-20 0,0 20,0 -20,20 0}

# rotate currently selected node
super + ctrl + {r,shift+r}
	bspc node -R {90,-90}
