#! /bin/sh

# launch programs that should restart when the wm restarts

pgrep -x sxhkd > /dev/null || sxhkd &

# fish $HOME/scripts/random-wp.fish &

fish $HOME/scripts/polybar-multimon.fish &

bspc rule -a KeePassXC --one-shot desktop=^5 && keepassxc &

wal -R &

picom &

# set wm colors using pywal

# source the colors.
. "${HOME}/.cache/wal/colors.sh"

# Set the border colors.
bspc config normal_border_color "$color1"
bspc config active_border_color "$color3"
bspc config focused_border_color "$foreground"
bspc config presel_feedback_color "$color1"

# Set desktops to monitors

# 2 monitors
bspc monitor DP-3 -d 1 2 3 4 5
bspc monitor DP-2 -d 6 7 8 9 10

# 1 monitor
# bspc monitor -d 1 2 3 4 5 6 7 8 9 10

bspc config border_width            3
bspc config window_gap              12

bspc config split_ratio             0.52
bspc config borderless_monocle      false
bspc config gapless_monocle         false
bspc config focus_follows_pointer   true
bspc config pointer_follows_monitor	true

bspc config ignore_ewmh_focus		true

bspc rule -a steam desktop="^4"
bspc rule -a discord desktop="^6" focus=off
bspc rule -a "RuneLite Launcher" state=floating
bspc rule -a "Spotify" desktop="^9" focus=off
