#! /bin/sh

# configure monitors
xrandr --newmode "1600x900-60.00"  118.25  1600 1696 1856 2112  900 903 908 934 -hsync +vsync
xrandr --addmode DP-2 1600x900-60.00
xrandr --output DP-3 --primary --mode 2560x1440 --pos 0x0 --output DP-2 --mode 1600x900-60.00 --pos 2560x312 --right-of DP-3 &

# launch programs that should restart when the wm restarts

pgrep -x sxhkd > /dev/null || sxhkd &

fish $HOME/scripts/random-wp.fish

fish $HOME/scripts/polybar-multimon.fish

bspc rule -a --one-shot keepassxc desktop="^5" && keepassxc &

# script to set wm colors using pywal

# source the colors.
. "${HOME}/.cache/wal/colors.sh"

# Set the border colors.
bspc config normal_border_color "$color2"
bspc config active_border_color "$color9"
bspc config focused_border_color "$foreground"
bspc config presel_feedback_color "$color1"

# Set desktops to monitors

# 2 monitors
bspc monitor DP-3 -d 1 2 3 4 5
bspc monitor DP-2 -d 6 7 8 9 10

# 1 monitor
# bspc monitor -d 1 2 3 4 5 6 7 8 9 10

bspc config border_width            3
bspc config window_gap              12

bspc config split_ratio             0.52
bspc config borderless_monocle      false
bspc config gapless_monocle         false
bspc config focus_follows_pointer   true

bspc rule -a steam desktop="^4"
bspc rule -a discord desktop="^6"
