# Default colors
[colors.primary]
background = '{background}'
foreground = '{foreground}'

dim_foreground    = '{background}'
bright_foreground = '{foreground}'

# Cursor colors
[colors.cursor]
text   = '{foreground}'
cursor = '{color9}'

# Normal colors
[colors.normal]
black   = '{color0}'
red     = '{color1}'
green   = '{color2}'
yellow  = '{color3}'
blue    = '{color4}'
magenta = '{color5}'
cyan    = '{color6}'
white   = '{color7}'

# Bright colors
[colors.bright]
black   = '{color8}'
red     = '{color9}'
green   = '{color10}'
yellow  = '{color11}'
blue    = '{color12}'
magenta = '{color13}'
cyan    = '{color14}'
white   = '{color3}'

# Dim colors
[colors.dim]
black   = '{color0}'
red     = '{color1}'
green   = '{color2}'
yellow  = '{color3}'
blue    = '{color4}'
magenta = '{color5}'
cyan    = '{color6}'
white   = '{color7}'
